
CREATE LOGIN apuestas with password='apuestas',
DEFAULT_DATABASE=APUESTAS
USE APUESTAS
CREATE USER apuestas FOR LOGIN apuestas
GRANT EXECUTE, INSERT, UPDATE,
SELECT TO apuestas

	BEGIN TRANSACTION

	INSERT INTO COMBATES (FECHA_INICIO, FECHA_FIN, ADMITE_APUESTAS, MAX_APUESTAS_POR_GANADOR, MAX_APUESTAS_POR_TIPO_VICTORIA, MAX_APUESTAS_POR_PUNTUACION) VALUES
	('01/5/21', '02/5/21', 1, 1000, 1000, 10000),
	('05/8/21', '06/8/21', 1, 1000, 1000, 1000)

    INSERT INTO COMPETICIONES (ID_COMBATE, NOMBRE_BOXEADOR) VALUES
    (3, 'Paco Abreu'),
    (3, 'Mac Janson'),
    (4, 'Antonio Sanjuan'),
    (4, 'Mac Janson')

	--ROLLBACK
	
	--SELECT * FROM COMBATES
	--SELECT * FROM APUESTAS
	--SELECT * FROM BOXEADORES

	COMMIT

	GO
	--Inserta una apuesta en la tabla apuestas y hace una insercion en la tabla tipo de apuestas
    CREATE OR ALTER PROCEDURE InstertarApuesta
        @NOMBRE_USUARIO VarChar(20),
        @ID_COMBATE Int,
        @CANTIDAD float,
        @CUOTA float,
        @GANADOR VARCHAR(50),
        @PUNTUACION SMALLINT,
        @TIPOVICTORIA VARCHAR(20)
    AS
    BEGIN
	BEGIN TRANSACTION
        INSERT INTO APUESTAS(NOMBRE_USUARIO,ID_COMBATE,CANTIDAD,CUOTA) VALUES (@NOMBRE_USUARIO,@ID_COMBATE,@CANTIDAD,@CUOTA)

        IF (@TIPOVICTORIA = 'JAVI' AND @PUNTUACION =-1)
            INSERT INTO APUESTAS_POR_GANADOR(ID_APUESTA, NOMBRE_GANADOR) VALUES (@@IDENTITY,@GANADOR)
        ELSE
            IF (@GANADOR = 'Indefinido' AND @PUNTUACION = -1)
                INSERT INTO APUESTAS_POR_TIPO_DE_VICTORIA(ID_APUESTA, TIPO_DE_VICTORIA) VALUES (@@IDENTITY,@TIPOVICTORIA)
            ELSE
                INSERT INTO APUESTAS_POR_PUNTUACION (ID_APUESTA, PUNTUACION) VALUES (@@IDENTITY, @PUNTUACION)
	COMMIT
    END
GO
select * from APUESTAS
--select * from BOXEADORES
--select * from COMBATES
select * from apuestas
--select * from APUESTAS_POR_GANADOR
select * from APUESTAS_POR_PUNTUACION
--select * from APUESTAS_POR_TIPO_DE_VICTORIA
--select * from USUARIOS
BEGIN TRANSACTION
EXECUTE InstertarApuesta 'Jesus',3, 3, 3, 'Paco Abreu', -1, 'JAVI'
EXECUTE InstertarApuesta 'Amador',3, 12, 3, 'Mac Janson', -1, 'JAVI'
EXECUTE InstertarApuesta 'Jesus',3, 3, 3, 'Paco Abreu', -1, 'JAVI'
ROLLBACK